### ISSUE TITLE
Missing depend file for UKB analyses

### ISSUE THREAD

**Issue by YaluWen** [mkelcb/shaprs-paper#1]
Hi there, 

Our group is very much interested in your method. We wish to run your codes provided in your ukbb_validation. However, we noticed the dependent file is not provided. Could you please upload this file? Thanks. 

# import local functions
sys.path.insert(0, '/home/ev250/myPypacks/pyrunPGS/pyrunPGS')
import geno_pgs

**Comment by mkelcb** [comment]
Thanks for reaching out. I've now added the missing file at:
https://github.com/mkelcb/shaprs-paper/blob/master/ukbb_validation/Scripts/geno_pgs.py
